# Generated by Django 5.0 on 2023-12-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_articles_articless'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articless',
            new_name='Articles',
        ),
    ]
